# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7a9ff09771b183b3946d9582f31f0aaa9555dafc68ce6daefbf7668767d4c03dd35ee8b9e903738ff0bfa506ad9ad45357e2368b1baaaadd35a7a41081b412

test:
  secret_key_base: 74a045308d78a199e51aa9225013c8b2004a12bdbfda04dbaf02eef8164b4faa5b8f4a293c42381ecbf7898a171c557d300188eb177e1585357a6653df31297f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
